/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Van Dao
 */
package smarthouse.ui;

import java.awt.Image;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

import smarthouse.engergy.EnergyManager;

public class UIManagingSmartObjects extends javax.swing.JFrame {

    /**
     * Creates new form UIManagingSmartObjects
     */
    public UIManagingSmartObjects(EnergyManager energyManager) throws IOException {
        this.energyManager = energyManager;
    	initComponents();
//        scaleImage();
    }
    
    
    public void scaleImage() throws IOException{
        //String currentPath = new java.io.File(".").getCanonicalPath();
        ImageIcon iconFan = new ImageIcon(getClass().getResource("Icon/fanon.png"));
        ImageIcon iconLightBulb = new ImageIcon(getClass().getResource("Icon/light.png"));
        ImageIcon iconHeater = new ImageIcon(getClass().getResource("Icon/heateron.png"));
        ImageIcon iconEnergy = new ImageIcon(getClass().getResource("Icon/energy.png"));
        ImageIcon iconBackground = new ImageIcon(getClass().getResource("Icon/smarthome2.jpg"));
        // scaling image fan
        Image imgFan = iconFan.getImage();
        Image imageScaleFan = imgFan.getScaledInstance(fan.getWidth(), fan.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconScaleFan = new ImageIcon(imageScaleFan);
        fan.setIcon(iconScaleFan);
        
        // scaling image light bulb
        Image imgLightBulb = iconLightBulb.getImage();
        Image imageScaleLightBulb = imgLightBulb.getScaledInstance(lightBulb.getWidth(), lightBulb.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconScaleLightBulb = new ImageIcon(imageScaleLightBulb);
        lightBulb.setIcon(iconScaleLightBulb);
        
        // scaling image heater
        Image imgHeater = iconHeater.getImage();
        Image imageScaleHeater = imgHeater.getScaledInstance(heater.getWidth(), heater.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconScaleHeater = new ImageIcon(imageScaleHeater);
        heater.setIcon(iconScaleHeater);
        
        // scaling image background
//        Image imgBackground = iconBackground.getImage();
//        Image imageScaleBackground = imgBackground.getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon iconScaleBackground = new ImageIcon(imageScaleBackground);
//        background.setIcon(iconScaleBackground);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        energyButton = new javax.swing.JButton();
        devicesButton = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
//        fan = new javax.swing.JLabel();
//        fanSource = new javax.swing.JComboBox<>();
//        onFanButton = new javax.swing.JButton();
//        offFanButton = new javax.swing.JButton();
//        heater = new javax.swing.JLabel();
//        heaterSource = new javax.swing.JComboBox<>();
//        onHeaterButton = new javax.swing.JButton();
//        offHeaterButton = new javax.swing.JButton();
//        lightBulb = new javax.swing.JLabel();
//        lightSource = new javax.swing.JComboBox<>();
//        onLightButton = new javax.swing.JButton();
//        offLightButton = new javax.swing.JButton();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        labelFanRate = new javax.swing.JLabel();
//        labelHeaterRate = new javax.swing.JLabel();
//        labelFanConsum = new javax.swing.JLabel();
//        labelLightRate = new javax.swing.JLabel();
//        labelHeaterConsum = new javax.swing.JLabel();
//        labelLightConsum = new javax.swing.JLabel();
//
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(100, 100));
//
        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
//
        energyButton.setText("Energy Source Management");
        energyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyButtonActionPerformed(evt);
            }
        });

        devicesButton.setText("Devices Management");
        devicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devicesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(energyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(devicesButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(devicesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(energyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );

        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//
//        fan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        EnergySource sourceList = new EnergySource();
//        fanSource.setModel(new javax.swing.DefaultComboBoxModel<>(sourceList.getList()));
////        fanSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "source 1", "Item 2", "Item 3", "Item 4" }));
//        fanSource.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                fanSourceActionPerformed(evt);
//            }
//        });
//
//        onFanButton.setText("ON");
//        onFanButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                onFanButtonActionPerformed(evt);
//            }
//        });
//
//        offFanButton.setText("OFF");
//        offFanButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                offFanButtonActionPerformed(evt);
//            }
//        });
//
//        heater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        heaterSource.setModel(new javax.swing.DefaultComboBoxModel<>(sourceList.getList()));
////        heaterSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
//
//        onHeaterButton.setText("ON");
//        onHeaterButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                onHeaterButtonActionPerformed(evt);
//            }
//        });
//
//        offHeaterButton.setText("OFF");
//        offHeaterButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                offHeaterButtonActionPerformed(evt);
//            }
//        });
//
//        lightBulb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        lightSource.setModel(new javax.swing.DefaultComboBoxModel<>(sourceList.getList()));
////        lightSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
//
//        onLightButton.setText("ON");
//        onLightButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                onLightButtonActionPerformed(evt);
//            }
//        });
//
//        offLightButton.setText("OFF");
//        offLightButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                offLightButtonActionPerformed(evt);
//            }
//        });
//
//        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
//        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel4.setText("Usage Rate");
//        jLabel4.setOpaque(true);
//
//        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
//        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel5.setText("Consumption");
//        jLabel5.setOpaque(true);
//
//        labelFanRate.setBackground(new java.awt.Color(255, 255, 255));
//        labelFanRate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        labelFanRate.setText("Fan Rate:");
//        labelFanRate.setOpaque(true);
//
//        labelHeaterRate.setBackground(new java.awt.Color(255, 255, 255));
//        labelHeaterRate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        labelHeaterRate.setText("Heater Rate:");
//        labelHeaterRate.setOpaque(true);
//
//        labelFanConsum.setBackground(new java.awt.Color(255, 255, 255));
//        labelFanConsum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        labelFanConsum.setText("Fan: ");
//        labelFanConsum.setOpaque(true);
//
//        labelLightRate.setBackground(new java.awt.Color(255, 255, 255));
//        labelLightRate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        labelLightRate.setText("Light Bulb Rate:");
//        labelLightRate.setOpaque(true);
//
//        labelHeaterConsum.setBackground(new java.awt.Color(255, 255, 255));
//        labelHeaterConsum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        labelHeaterConsum.setText("Heater:");
//        labelHeaterConsum.setOpaque(true);
//
//        labelLightConsum.setBackground(new java.awt.Color(255, 255, 255));
//        labelLightConsum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        labelLightConsum.setText("Light Bulb:");
//        labelLightConsum.setOpaque(true);
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                            .addComponent(onLightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addGap(12, 12, 12)
//                            .addComponent(offLightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                            .addGap(26, 26, 26)
//                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                .addComponent(lightBulb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addComponent(lightSource, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                            .addGap(59, 59, 59)
//                            .addComponent(fan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                            .addGap(59, 59, 59)
//                            .addComponent(fanSource, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                            .addGap(33, 33, 33)
//                            .addComponent(onFanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addGap(12, 12, 12)
//                            .addComponent(offFanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(onHeaterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(12, 12, 12)
//                                .addComponent(offHeaterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGap(26, 26, 26)
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addComponent(heater, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(heaterSource, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                        .addGap(182, 182, 182))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                    .addComponent(labelFanRate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(labelHeaterRate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(73, 73, 73))
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(labelLightRate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(23, 23, 23)))
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(labelLightConsum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(labelFanConsum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(labelHeaterConsum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(85, 85, 85))))
//        );
//        jPanel2Layout.setVerticalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addGap(28, 28, 28)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                        .addComponent(heater, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(6, 6, 6)
//                        .addComponent(heaterSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(6, 6, 6)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(onHeaterButton)
//                            .addComponent(offHeaterButton)))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                        .addComponent(fan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(6, 6, 6)
//                        .addComponent(fanSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(6, 6, 6)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(onFanButton)
//                            .addComponent(offFanButton))))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(lightBulb, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel4)
//                            .addComponent(jLabel5))
//                        .addGap(18, 18, 18)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(labelFanRate)
//                            .addComponent(labelFanConsum))))
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGap(6, 6, 6)
//                        .addComponent(lightSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(6, 6, 6)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(onLightButton)
//                            .addComponent(offLightButton)))
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGap(3, 3, 3)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(labelHeaterRate)
//                            .addComponent(labelHeaterConsum))
//                        .addGap(18, 18, 18)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(labelLightRate)
//                            .addComponent(labelLightConsum))))
//                .addGap(64, 64, 64))
//        );

        jTabbedPane.addTab("Devices Management", jPanel2);

		this.energySourceMgmtPanel = new EnergySourceManagementUI(this.energyManager); // [FIXME] should be energySource from constructor
//        Thread energyUIThre2ad = new Thread (this.energySourceMgmtPanel);
//        energyUIThread.start();

        jTabbedPane.addTab("Energy Source Management", this.energySourceMgmtPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void energyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyButtonActionPerformed
        // TODO add your handling code here:
    	jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_energyButtonActionPerformed

    private void devicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devicesButtonActionPerformed
        // TODO add your handling code here:
    	jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_devicesButtonActionPerformed

    private void fanSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fanSourceActionPerformed
        // TODO add your handling code here:
//        String[] sourceName = {"Source 1", "Source 2", "Source 3", "Source 4"};
//        fanSource.setModel(new javax.swing.DefaultComboBoxModel<>(sourceName));
    }//GEN-LAST:event_fanSourceActionPerformed

    private void onFanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFanButtonActionPerformed
        // TODO add your handling code here:
        int a = fanSource.getSelectedIndex();
        labelFanConsum.setText("Fan: " + a);
        labelFanRate.setText("Fan Rate: " + a);
    }//GEN-LAST:event_onFanButtonActionPerformed

    private void offFanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offFanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offFanButtonActionPerformed

    private void onHeaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onHeaterButtonActionPerformed
        // TODO add your handling code here:
        int a = heaterSource.getSelectedIndex();
        labelHeaterConsum.setText("Heater: " + a);
        labelHeaterRate.setText("Heater Rate: " + a);
    }//GEN-LAST:event_onHeaterButtonActionPerformed

    private void offHeaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offHeaterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offHeaterButtonActionPerformed

    private void onLightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLightButtonActionPerformed
        // TODO add your handling code here:
        int a = lightSource.getSelectedIndex();
        labelLightConsum.setText("Light Bulb: " + a);
        labelLightRate.setText("Light Bulb Rate: " + a);
    }//GEN-LAST:event_onLightButtonActionPerformed

    private void offLightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offLightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offLightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UIManagingSmartObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UIManagingSmartObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UIManagingSmartObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UIManagingSmartObjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new UIManagingSmartObjects().setVisible(true);
//                } catch (IOException ex) {
//                    Logger.getLogger(UIManagingSmartObjects.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    private EnergySourceManagementUI energySourceMgmtPanel; 
    private EnergyManager energyManager;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devicesButton;
    private javax.swing.JButton energyButton;
    private javax.swing.JLabel fan;
    private javax.swing.JComboBox<String> fanSource;
    private javax.swing.JLabel heater;
    private javax.swing.JComboBox<String> heaterSource;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel labelFanConsum;
    private javax.swing.JLabel labelFanRate;
    private javax.swing.JLabel labelHeaterConsum;
    private javax.swing.JLabel labelHeaterRate;
    private javax.swing.JLabel labelLightConsum;
    private javax.swing.JLabel labelLightRate;
    private javax.swing.JLabel lightBulb;
    private javax.swing.JComboBox<String> lightSource;
    private javax.swing.JButton offFanButton;
    private javax.swing.JButton offHeaterButton;
    private javax.swing.JButton offLightButton;
    private javax.swing.JButton onFanButton;
    private javax.swing.JButton onHeaterButton;
    private javax.swing.JButton onLightButton;
    // End of variables declaration//GEN-END:variables
}
